from typing import List, Dict

class HTMLRenderer:
    """Responsible solely for generating HTML output (Separation of Concerns)."""
    
    @staticmethod
    def render_newsletter(intro_text: str, articles: List[Dict[str, str]]) -> str:
        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>AI Daily Newsletter</title>
            <style>
                body {{ font-family: 'Inter', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
                h1 {{ color: #2c3e50; text-align: center; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                .intro {{ font-size: 1.1em; margin-bottom: 30px; font-style: italic; color: #555; background: #fdfdfd; padding: 15px; border-radius: 8px; border-left: 4px solid #3498db;}}
                .article {{ margin-bottom: 30px; padding-bottom: 20px; border-bottom: 1px solid #eee; }}
                .article img {{ max-width: 100%; height: auto; border-radius: 8px; margin-bottom: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
                .article h2 {{ color: #2980b9; margin-top: 0; }}
                .article p {{ margin-bottom: 15px; color: #444; }}
                .read-more {{ display: inline-block; background: #3498db; color: #fff; text-decoration: none; padding: 8px 15px; border-radius: 5px; font-weight: bold; transition: background 0.3s; }}
                .read-more:hover {{ background: #2980b9; }}
                .footer {{ text-align: center; margin-top: 40px; font-size: 0.9em; color: #777; }}
            </style>
        </head>
        <body>
            <h1>🔥 Top 10 Trending AI News</h1>
            <div class="intro">
                <p>{intro_text}</p>
            </div>
        """

        for idx, article in enumerate(articles, 1):
            title = article.get("title", "No Title")
            desc = article.get("description", "No Description")
            url = article.get("url", "#")
            img_url = article.get("urlToImage", "")

            img_tag = f'<img src="{img_url}" alt="{title}">' if img_url else ''

            html_content += f"""
            <div class="article">
                <h2>{idx}. {title}</h2>
                {img_tag}
                <p>{desc}</p>
                <a href="{url}" class="read-more" target="_blank">Read More</a>
            </div>
            """

        html_content += """
            <div class="footer">
                <p>Generated by your AI LinkedIn Automation Tool</p>
            </div>
        </body>
        </html>
        """
        
        return html_content
